-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL U2725QE 5Z1FMF4",
  mode = "3840x2160@60.00",
  position = "5863x0",
  scale = 1.66667,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG HDR 4K 0x0004A5D4",
  mode = "3840x2160@60.00",
  position = "3557x0",
  scale = 1.66667,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "SUNSHINE",
  mode = "1920x1080@60.00",
  position = "8309x0",
  scale = 1.66667,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "desc:Dell Inc. DELL U2725QE 5Z1FMF4", persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "desc:LG Electronics LG HDR 4K 0x0004A5D4", default = true, persistent = true })
