# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c1375c99-e949-4d35-a5ba-03527a86f07f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c1375c99-e949-4d35-a5ba-03527a86f07f".device = "/dev/disk/by-uuid/c1375c99-e949-4d35-a5ba-03527a86f07f";
  boot.initrd.luks.devices."luks-32725764-cfd3-401c-aa05-b59f366b20b4".device = "/dev/disk/by-uuid/32725764-cfd3-401c-aa05-b59f366b20b4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B417-A3EA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-32725764-cfd3-401c-aa05-b59f366b20b4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
