# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vmd"
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-8dce0af5-f867-40c7-b060-02f5af164340";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8dce0af5-f867-40c7-b060-02f5af164340".device =
    "/dev/disk/by-uuid/8dce0af5-f867-40c7-b060-02f5af164340";
  boot.initrd.luks.devices."luks-faf7f7e5-6171-4339-9e32-bd7a858c8ae2".device =
    "/dev/disk/by-uuid/faf7f7e5-6171-4339-9e32-bd7a858c8ae2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DE1B-78C0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-faf7f7e5-6171-4339-9e32-bd7a858c8ae2"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
