name: "nix"
on:
  push:
    branches: [main]

jobs:
  check:
    name: "validate flake configurations"
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: P1DT12H
          purge-primary-key: never
      - name: "Validate flake outputs"
        run: |
          nix flake show
          nix eval --raw .#nixosConfigurations.mini.config.system.build.toplevel.type
          nix eval --raw .#nixosConfigurations.wsl.config.system.build.toplevel.type
          nix eval --raw .#nixosConfigurations.mediastation.config.system.build.toplevel.type
          nix eval --raw .#nixosConfigurations.macmini.config.system.build.toplevel.type
          nix eval --raw .#nixosConfigurations.dell-workstation.config.system.build.toplevel.type
          nix eval --raw .#nixosConfigurations.installer.config.system.build.toplevel.type
          nix eval --raw .#darwinConfigurations.macbook-pro-osx.system.type
          nix eval --raw .#homeConfigurations.hpc.activationPackage.type
  # build:
  #   name: "nix build"
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: cachix/install-nix-action@v31
  #       with:
  #         extra_nix_config: |
  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
  #     - uses: nix-community/cache-nix-action@v7
  #       with:
  #         primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
  #         restore-prefixes-first-match: nix-${{ runner.os }}-
  #         gc-max-store-size-linux: 1G
  #         purge: true
  #         purge-prefixes: nix-${{ runner.os }}-
  #         purge-created: 0
  #         purge-last-accessed: P1DT12H
  #         purge-primary-key: never
  #     - name: "nix build"
  #       run: nix build -Lvvv --no-update-lock-file --show-trace --print-build-logs
