name: "nix"
on:
  push:
    branches: [main]

jobs:
  check:
    name: "nix flake check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
      - name: "nix flake check"
        run: nix flake check -L
  # build:
  #   name: "nix build"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: cachix/install-nix-action@v31
  #       with:
  #         extra_nix_config: |
  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
  #     - uses: DeterminateSystems/magic-nix-cache-action@v13
  #       with:
  #         diagnostic-endpoint: ""
  #     - name: "nix build"
  #       run: nix build -Lvvv --no-update-lock-file --show-trace --print-build-logs
